repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
        args: [ --autofix, --indent=2]
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
